services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets_manager_api
    ports:
      - "8000:8000"
    env_file:
      - ticket_mgmt.env
    environment:
      - ENV=${ENV:-DEV}
    restart: unless-stopped
